# Generated by Django 6.0.5 on 2026-06-08 08:40

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='baskets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, editable=False),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)]), default=list),
        ),
    ]
