# Generated by Django 6.0.5 on 2026-06-01 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_productmodel_alter_usermodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='tags',
            field=models.CharField(default='', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
            preserve_default=False,
        ),
    ]
